BEGIN;
ALTER TABLE auth.users
    ADD COLUMN IF NOT EXISTS login_attempts INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS login_window_started_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE auth.verification_codes
    ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0;
COMMIT;
